### ISSUE TITLE
fix/entity-renewal

### ISSUE THREAD

**Issue by Kwak-JunYoung** [Meteor-hanaro/Backend#22]
## 📌 Feature Issue

JWT 인증으로 인해 entity 구조를 바꾸고, 잘못 구현된 부분들 수정 예정입니다.

## 📝 To-do

- [x] VIP table 신설
- [x] user table 변경
- [x] role table 신설
- [ ] pb table 변경
- [ ] risktype-vip 관계 재설정
- [x] portfolio-vip 관계 재설정
- [ ] risktype-fund 관계 재설정
- [ ] fund-portfolio_item 관계 재설정
- [ ] fund-suggestion_item 관계 재설정
