### ISSUE TITLE
feature/pb-main

### ISSUE THREAD

**Issue by kgw0124** [Meteor-hanaro/Backend#30]
## 📌 Feature Issue

/api/pb/main 구현

## 📝 To-do

- [x] pb 기본 정보 불러오기
- [x] pb 소속 vip 목록 불러오기
- [ ] 각 vip의 로그인 여부 불러오기 : vip login 구현 후 개발 예정
