### ISSUE TITLE
feature/vip-main

### ISSUE THREAD

**Issue by kgw0124** [Meteor-hanaro/Backend#35]
## 📌 Feature Issue

/api/vip/main 구현

## 📝 To-do

- [x] vip 기본 정보 불러오기
- [x] 담당 pb 기본 정보 불러오기
- [x] 상담 이력 불러오기
