### ISSUE TITLE
feature/finalContract&portfolioRenewal

### ISSUE THREAD

**Issue by jiyeoon00** [Meteor-hanaro/Backend#59]
## 📌 Feature Issue

최종 계약 완료 버튼을 눌렀을 때 , 서버에서 처리해야 할 로직을 구현합니다.

## 📝 To-do

- [x] 서명된 계약서와 함께 최종 계약 성사
- [x] 계약서 암호화 기능
- [x] 선택된 수정안으로 포트폴리오 갱신
