### ISSUE TITLE
feature/system_admin

### ISSUE THREAD

**Issue by tkdalsss** [Meteor-hanaro/Backend#70]
## 📌 Feature Issue

시스템 관리자 페이지에 필요한 데이터 및 로직 구현

## 📝 To-do

- [x] 시스템 관리자 비밀번호 확인 로직 구현
- [x] 시스템 관리자 페이지에 필요한 데이터 추출 로직 구현
- [x] 시스템 관리자 페이지에 필요한 데이터를 위한 responsedto 구현(기존 dto를 최대한 활용하는 쪽으로)
